# Cardano Block Fetcher Configuration
# This file configures the blockfetcher component of firehose-cardano

# Cardano node address to connect to
address = "backbone.cardano.iog.io:3001"

# Cardano network to connect to: "mainnet", "preview", or "preprod"
network = "mainnet"

# Network magic number (0 means auto-detect from network)
network_magic = 0

# Pipeline limit for block fetching (number of concurrent requests)
pipeline_limit = 10

# Starting slot number for block fetching (0 means start from current tip)
start_slot = 164220519

# Starting block hash for block fetching (empty means use current tip)
start_hash = "e37eb9e1b9bacbff9a64f3ccc737cc3a445d09fb30c43f698ca111a56a7af777"

# Example configurations for different networks:

# For mainnet:
# address = "backbone.cardano.iog.io:3001"
# network = "mainnet"
# network_magic = 764824073

# For preview testnet:
# address = "backbone.cardano-preview.iog.io:3001"
# network = "preview"
# network_magic = 2

# For preprod testnet:
# address = "backbone.cardano-preprod.iog.io:3001"
# network = "preprod"
# network_magic = 1
